"""Add premium columns to user

Revision ID: 479f43a8784d
Revises: ae37b0d5d772
Create Date: 2026-01-19 16:11:12.951609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479f43a8784d'
down_revision: Union[str, Sequence[str], None] = 'ae37b0d5d772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('premium_expiry', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_is_premium'), 'users', ['is_premium'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_premium'), table_name='users')
    op.drop_column('users', 'premium_expiry')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
